// Generated by CoffeeScript 1.6.2
var DomFactory,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

DomFactory = (function(_super) {
  __extends(DomFactory, _super);

  /*
  */


  DomFactory.prototype.name = "dom";

  /*
  */


  function DomFactory() {}

  /*
  */


  DomFactory.prototype.createElement = function(name) {
    return document.createElement(name);
  };

  /*
  */


  DomFactory.prototype.createTextNode = function(text) {
    return document.createTextNode(text);
  };

  /*
  */


  DomFactory.prototype.createFragment = function(children) {
    var child, childrenToArray, frag, _i, _j, _len, _len1;

    if (children == null) {
      children = [];
    }
    frag = document.createDocumentFragment();
    childrenToArray = [];
    for (_i = 0, _len = children.length; _i < _len; _i++) {
      child = children[_i];
      childrenToArray.push(child);
    }
    for (_j = 0, _len1 = childrenToArray.length; _j < _len1; _j++) {
      child = childrenToArray[_j];
      frag.appendChild(child);
    }
    return frag;
  };

  /*
  */


  DomFactory.prototype.parseHtml = function(text) {
    var div;

    div = this.createElement("div");
    div.innerHTML = text;
    return this.createFragment.apply(this, div.childNodes);
  };

  return DomFactory;

})(require("./base"));

module.exports = new DomFactory();
